<?php get_header(); get_template_part('slider'); ?>
<main class="content-zone"><div class="recovery-strip"><strong>Bản demo phục dựng:</strong> giao diện dựa trên HTML/CSS và tài nguyên còn lại của website Joomla cũ; nội dung được khôi phục dần từ tài liệu gốc.</div><div class="home-grid"><section>
<div class="panel"><h2 class="panel-title">Tin tức / Công bố mới phục hồi</h2><div class="panel-body">
<?php $q=new WP_Query(['post_type'=>'post','post_status'=>'publish','posts_per_page'=>7,'orderby'=>'date','order'=>'DESC']); if($q->have_posts()): while($q->have_posts()):$q->the_post(); ?><article class="news-item"><h3><a href="<?php the_permalink(); ?>"><?php the_title(); ?></a></h3><div class="news-meta"><?php echo esc_html(get_the_date('d/m/Y')); ?><?php if($s=pvdmcn_demo_status()): ?> · <?php echo esc_html($s); ?><?php endif; ?></div></article><?php endwhile; wp_reset_postdata(); else: ?><p>Chưa có bài viết phục hồi.</p><?php endif; ?>
</div></div>
<div class="panel"><h2 class="panel-title">Tài liệu doanh nghiệp</h2><div class="panel-body"><ul class="documents-list"><?php $docs=pvdmcn_demo_docs(10); if($docs): foreach($docs as $d): ?><li><a href="<?php echo esc_url(pvdmcn_demo_doc_url($d)); ?>" target="_blank" rel="noopener"><?php echo esc_html(get_the_title($d)); ?></a></li><?php endforeach; else: ?><li>Chưa có dữ liệu tài liệu. Hãy kích hoạt PVDMCN Rebuild Toolkit và chạy seed.</li><?php endif; ?></ul></div></div>
</section><aside>
<div class="panel"><h2 class="panel-title">Sản phẩm</h2><div class="panel-body"><ul class="side-list"><li><a href="<?php echo esc_url(home_url('/san-pham/san-pham-chu-yeu/')); ?>">Sản phẩm chủ yếu</a></li><li><a href="<?php echo esc_url(home_url('/san-pham/hoa-chat-dung-dich-khoan/')); ?>">Hóa chất dung dịch khoan</a></li><li><a href="<?php echo esc_url(home_url('/san-pham/san-pham-loc-hoa-dau/')); ?>">Sản phẩm lọc hóa dầu</a></li><li><a href="<?php echo esc_url(home_url('/san-pham/san-pham-khac/')); ?>">Sản phẩm khác</a></li></ul></div></div>
<div class="panel"><h2 class="panel-title">Quan hệ cổ đông</h2><div class="panel-body"><ul class="side-list"><li><a href="<?php echo esc_url(home_url('/quan-he-co-dong/bao-cao-thuong-nien/')); ?>">Báo cáo thường niên</a></li><li><a href="<?php echo esc_url(home_url('/quan-he-co-dong/bao-cao-quan-tri/')); ?>">Báo cáo quản trị</a></li><li><a href="<?php echo esc_url(home_url('/quan-he-co-dong/bao-cao-tai-chinh/')); ?>">Báo cáo tài chính</a></li><li><a href="<?php echo esc_url(home_url('/quan-he-co-dong/dai-hoi-dong-co-dong/')); ?>">Đại hội đồng cổ đông</a></li></ul></div></div>
<div class="panel"><h2 class="panel-title">Dịch vụ</h2><div class="panel-body"><ul class="side-list"><li><a href="<?php echo esc_url(home_url('/dich-vu/hoat-dong-logistics/')); ?>">Một số hoạt động logistics</a></li><li><a href="<?php echo esc_url(home_url('/quan-ly-chat-luong/')); ?>">Quản lý chất lượng</a></li><li><a href="<?php echo esc_url(home_url('/lien-he/')); ?>">Liên hệ</a></li></ul></div></div>
</aside></div></main>
<?php get_template_part('activity-strip'); get_footer(); ?>
